apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: srinjchadb
  name: srinjchadb
  namespace: srinjcha-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srinjchadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: srinjchadb
    spec:
      volumes:
      - name: srinjchadbvol
        hostPath:
         path: /data/srinjchadb
         type: DirectoryOrCreate
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: srinjchadb-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: srinjchadb-sec
              key: db_pass
        - name: MySQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: srinjchadb-sec
              key: root_pass
        resources: {}
        volumeMounts:
        - name: srinjchadbvol
          mountPath: /var/lib/mysql/
status: {}
